FORMAT: 1A
HOST: http://itas.apiary.io/
VERSION: 1.0

# COFCO Custom API v1.0

<br />
<strong>Release notes</strong> (<sup>2nd</sup> February 2024.)

## New Endpoints

<ul>
<li>None</li>
</ul>

## Updated Endpoints

<ul>
<li>Finance-Cash <b>Create PayableOnAccount</b>: Additional Property AlternateClientCode,<a href="/#reference/finance-cash/payableonaccount"> Link</a></li>
</ul>
<chandiv>** ends ** </div>


## AccessToken [/AT]
Model Header containing AccessToken

+ Model 
    + Header

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg


# Group Client Ledger Data

## Client Ledger Account [/ClientLedger/{TradingEntityId}/ClientAccount/{ClientAccountId}]

### Create Client Ledger Account [PUT]
`PUT`

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|ClientAccountId|Client Account ID|`string`|10||Required. Unique Key|
|Title|Client Account Title|`string`|200||Required|
|CountryCode|Country Code|`string`|3||Required|
|ShortName|Short Name|`string`|100|||
|ClientTypeCode|Client Account Type Code|`string`|1|||
|Status|Account Status|`string`|1||`O` or `F`, default `O`|
|AddressLine1|Address Line 1|`string`|60|||
|AddressLine2|Address Line 2|`string`|60|||
|AddressLine3|Address Line 3|`string`|60|||
|AddressLine4|Address Line 4|`string`|60|||
|ZipCode|Zip Code|`string`|40|||
|City|City|`string`|20|||
|Province|Province|`string`|4|||
|EmailAddress|Email Address|`string`|100|||
|PhoneNumber|Phone Number|`string`|40|||
|FaxNumber|Fax Number|`string`|40|||
|CountryOfIncCode|Country of Incorporation Code|`string`|3|||
|HeadOfFamilyAccountCode|Head of Family Account Code|`string`|10|||
|CanBeBuyer|Is Client a Buyer|`boolean`||||
|CanBeSeller|Is Client a Seller|`boolean`||||
|CanBeShipper|Is Client a Shipper|`boolean`||||
|CanBeWarehouse|Is Client a Warehouse|`boolean`||||
|CanBeAgent|Is Client an Agent|`boolean`||||
|CanBeDeliveryAccount|Is Client a Delivery Account|`boolean`||||
|CanBe3rdParty|Is Client a 3rd Party|`boolean`||||
|CanBeDerivativeClient|Is Client a Derivative Client|`boolean`||||
|CanBeDerivativeBroker|Is Client a Derivative Broker|`boolean`||||
|CanBeIntroBroker|Is Client an Intro Broker|`boolean`||||
|CanBeBank|Is Client a Bank|`boolean`||||
|CanBeDistributer|Is Client a Distributer|`boolean`||||
|CanBeService|Is Client a Service|`boolean`||||
|CanBeProjectSponsor|Is Client a Project Sponsor|`boolean`||||
|CanBeProjectManager|Is Client a Project Manager|`boolean`||||
|CanBeContractor|Is Client a Contractor|`boolean`||||
|CanBeGiveUp|Is Client a GiveUp|`boolean`||||
|CanBeAssociation|Is Client an Association|`boolean`||||
|CanBeHaulier|Is Client a Haulier|`boolean`||||
|CanBeMill|Is Client a Mill|`boolean`||||
|CanBeForwarder|Is Client a Forwarder|`boolean`||||
|CanBeController|Is Client a Controller|`boolean`||||
|CanBeGrower|Is Client a Grower|`boolean`||||
|CanBeFloorBroker|Is Client a Floor Broker|`boolean`||||
|CanBePrivatePerson|Is Client a Private Person|`boolean`||||
|CanBeStockManager|Is Client a Stock Manager|`boolean`||||
|CanBeNotify|Is Client a Notify|`boolean`||||
|CanBeStaff|Is Client a Staff|`boolean`||||
|CanBeSampleSenderReceiver|Is Client a Staff|`boolean`||||
|ClientBankAccounts|See <b><a href="/#reference/data-object-definitions/client-bank-account">Client Bank Account object</a></b> |[array] of `object`||||
|ClientInterfaceCodes|See <b><a href="/#reference/data-object-definitions/client-interface-code">Client Interface Code object</a></b> |[array] of `object`||||
|ClientExtraVATRegistrations|See <b><a href="/#reference/data-object-definitions/client-extra-vat-registration">Client Extra VAT Registration object</a></b> |[array] of `object`||||


+ Request (application/json)
    + Header

            AccessToken:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

    + Attributes (ClientAccountCreate)

+ Parameters
    + TradingEntityId (required, string, `JT`) ... Identify specific trading entity.
    + ClientAccountId (required, string, `ABCDEF.P`) ... Code for client account to create.

+ Response 201 (application/json; charset=utf-8)
    + Attributes 
        + Data
            + ClientAccountId: ABCDEF.P (string)
        + Response (201 CreateResponse)
        + Messages (array [201 ErrorMessageDetail])
    
+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 Response)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)

+ Response 405 (application/json; charset=utf-8)
    + Attributes (405 Response)

### Update Client Ledger Account [PATCH]
`PATCH`

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|ClientAccountId|Client Account ID|`string`|10||Required|
|Title|Client Account Title|`string`|200|||
|CountryCode|Country Code|`string`|3|||
|ShortName|Short Name|`string`|100|||
|ClientTypeCode|Client Account Type Code|`string`|1|||
|Status|Account Status|`string`|1||`O` or `F`|
|AddressLine1|Address Line 1|`string`|60|||
|AddressLine2|Address Line 2|`string`|60|||
|AddressLine3|Address Line 3|`string`|60|||
|AddressLine4|Address Line 4|`string`|60|||
|ZipCode|Zip Code|`string`|40|||
|City|City|`string`|20|||
|Province|Province|`string`|4|||
|EmailAddress|Email Address|`string`|100|||
|PhoneNumber|Phone Number|`string`|40|||
|FaxNumber|Fax Number|`string`|40|||
|CountryOfIncCode|Country of Incorporation Code|`string`|3|||
|HeadOfFamilyAccountCode|Head of Family Account Code|`string`|10|||
|CanBeBuyer|Is Client a Buyer|`boolean`||||
|CanBeSeller|Is Client a Seller|`boolean`||||
|CanBeShipper|Is Client a Shipper|`boolean`||||
|CanBeWarehouse|Is Client a Warehouse|`boolean`||||
|CanBeAgent|Is Client an Agent|`boolean`||||
|CanBeDeliveryAccount|Is Client a Delivery Account|`boolean`||||
|CanBe3rdParty|Is Client a 3rd Party|`boolean`||||
|CanBeDerivativeClient|Is Client a Derivative Client|`boolean`||||
|CanBeDerivativeBroker|Is Client a Derivative Broker|`boolean`||||
|CanBeIntroBroker|Is Client an Intro Broker|`boolean`||||
|CanBeBank|Is Client a Bank|`boolean`||||
|CanBeDistributer|Is Client a Distributer|`boolean`||||
|CanBeService|Is Client a Service|`boolean`||||
|CanBeProjectSponsor|Is Client a Project Sponsor|`boolean`||||
|CanBeProjectManager|Is Client a Project Manager|`boolean`||||
|CanBeContractor|Is Client a Contractor|`boolean`||||
|CanBeGiveUp|Is Client a GiveUp|`boolean`||||
|CanBeAssociation|Is Client an Association|`boolean`||||
|CanBeHaulier|Is Client a Haulier|`boolean`||||
|CanBeMill|Is Client a Mill|`boolean`||||
|CanBeForwarder|Is Client a Forwarder|`boolean`||||
|CanBeController|Is Client a Controller|`boolean`||||
|CanBeGrower|Is Client a Grower|`boolean`||||
|CanBeFloorBroker|Is Client a Floor Broker|`boolean`||||
|CanBePrivatePerson|Is Client a Private Person|`boolean`||||
|CanBeStockManager|Is Client a Stock Manager|`boolean`||||
|CanBeNotify|Is Client a Notify|`boolean`||||
|CanBeStaff|Is Client a Staff|`boolean`||||
|CanBeSampleSenderReceiver|Is Client a Staff|`boolean`||||

+ Request (application/json)
    + Header

            AccessToken:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

    + Attributes (ClientAccountUpdate)

+ Parameters
    + TradingEntityId (required, string, `JT`) ... Identify specific trading entity.
    + ClientAccountId (required, string, `ABCDEF.P`) ... Code for client account to create.

+ Response 200 (application/json; charset=utf-8)
    + Attributes 
        + Data
            + ClientAccountId: ABCDEF.P (string)
        + Response (200 UpdateResponse)
        + Messages (array [201 ErrorMessageDetail])
    
+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 Response)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)

+ Response 405 (application/json; charset=utf-8)
    + Attributes (405 Response)

### Delete Client Ledger Account [DELETE]
`DELETE`

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|ClientAccountId|Client Account ID|`string`|10||Required|

<strong>Body Parameters</strong>
<br />
None.


+ Request (application/json)
    + Header

            AccessToken:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

    + Body 
    
            {
                none
            }

+ Parameters
    + TradingEntityId (required, string, `JT`) ... Identify specific trading entity.
    + ClientAccountId (required, string, `ABCDEF.P`) ... Code for client account to delete.

+ Response 200 (application/json; charset=utf-8)
    + Attributes 
        + Data
            + ClientAccountId: ABCDEF.P (string)
        + Response (200 DeletedResponse)
    
+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 Response)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)

+ Response 405 (application/json; charset=utf-8)
    + Attributes (405 Response)

## Client Ledger Bank Account [/ClientLedger/{TradingEntityId}/ClientBankAccount/{ClientAccountId}/{BankAccountName}/{BankAccountNumber}]

### Update Client Ledger Bank Account [PATCH]
`PATCH`

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|ClientAccountId|Client Account ID|`string`|10||Required|
|BankAccountName|Bank Account Name|`string`|40||Required|
|BankAccountNumber|Bank Account Number|`string`|34||Required|
|CountryCode|Country Code|`string`|3|||
|BankNumber|Bank Number|`number`||||
|IBANNumber|IBAN Number|`string`|34|||
|CurrencyCode|Currency Code|`string`|3|||
|Status|Account Status|`string`|1||`O` or `F`|

+ Request (application/json)
    + Header

            AccessToken:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

    + Attributes (ClientAccountUpdate)

+ Parameters
    + TradingEntityId (required, string, `JT`) ... Identify specific trading entity.
    + ClientAccountId (required, string, `ABCDEF.P`) ... 
    + BankAccountName (required, string, `Barclays`) ... 
    + BankAccountNumber (required, string, `111000111`) ... 

+ Response 200 (application/json; charset=utf-8)
    + Attributes 
        + Data
            + ClientAccountId: ABCDEF.P (string)
            + BankAccountName: Barclays (string)
            + BankAccountNumber: 111000111 (string)
        + Response (200 UpdateResponse)
        + Messages (array [201 ErrorMessageDetail])
    
+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 Response)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)

+ Response 405 (application/json; charset=utf-8)
    + Attributes (405 Response)

### Delete Client Ledger Bank Account [DELETE]
`DELETE`

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|ClientAccountId|Client Account ID|`string`|10||Required|
|BankAccountName|Bank Account Name|`string`|40||Required|
|BankAccountNumber|Bank Account Number|`string`|34||Required|

<strong>Body Parameters</strong>
<br />
None.


+ Request (application/json)
    + Header

            AccessToken:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

    + Body 
    
            {
                none
            }

+ Parameters
    + TradingEntityId (required, string, `JT`) ... Identify specific trading entity.
    + ClientAccountId (required, string, `ABCDEF.P`) ... 
    + BankAccountName (required, string, `Barclays`) ... 
    + BankAccountNumber (required, string, `111000111`) ... 

+ Response 200 (application/json; charset=utf-8)
    + Attributes 
        + Data
            + ClientAccountId: ABCDEF.P (string)
            + BankAccountName: Barclays (string)
            + BankAccountNumber: 111000111 (string)
        + Response (200 DeletedResponse)
    
+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 Response)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)

+ Response 405 (application/json; charset=utf-8)
    + Attributes (405 Response)


# Group Data Object Definitions
List of re-usable Data Objects referenced as `object` types. Not that these endpoints are not accessable and only here for reference purposes.

## Client Bank Account [/ClientBankAccount]
A multipurpose object used by several endpoints
### ClientBankAccount[PUT]

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|BankAccountName|Bank Account Name|`string`|40||Required|
|BankAccountNumber|Bank Account Number|`string`|34||Required|
|CountryCode|Country Code|`string`|3|||
|BankNumber|Bank Number|`number`||||
|IBANNumber|IBAN Number|`string`|34|||
|CurrencyCode|Currency Code|`string`|3|||
|Status|Account Status|`string`|1||`O` or `F`, default `O`|

+ Response 200 (application/json; charset=utf-8)
+ Attributes (ClientBankAccountObject)


## Client Extra VAT Registration [/ClientExtraVatRegistration]
A multipurpose object used by several endpoints
### ClientExtraVatRegistration[PUT]

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|VATRegistrationNumber|VAT Registration Number|`string`|20||Required|
|CountryCode|Country Code|`string`|3|||
|IDNumber|ID Number|`string`|255|||
|EORINumber|EORI Number|`string`|20|||

+ Response 200 (application/json; charset=utf-8)
+ Attributes (ClientExtraVatObject)

## Client Interface Code [/ClientInterfaceCode]
A multipurpose object used by several endpoints
### ClientInterfaceCode[PUT]

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|InterfaceTypeCode|Interface Type Code|`string`|8||Required|
|CodeMapping|Code Mapping|`string`|20||Required|

+ Response 200 (application/json; charset=utf-8)
+ Attributes (ClientInterfaceCodeObject)


# Data Structures

## 200 SuccessResponse (object)
+ Value: Success (string)

## 200 UpdateResponse (object)
+ Value: Updated (string)

## 200 DeletedResponse (object)
+ Value: Deleted (string)

## 200 AuthoriseResponse (object)
+ Value: Authorised (string)

## 201 CreateResponse (object)
+ Value: Created (string)

## 201 CreateMessages (object)
+ Messages (array [201 ErrorMessageDetail])

## 201 ErrorMessageDetail (object)
+ Severity: Warning (string)
+ Message: `API5084 - API : {fieldName} has a {fieldName} of {value}.` (string)

## 201 CreateBllMessages (object)
+ Messages (array [201 ErrorBllMessageDetail])

## 201 ErrorBllMessageDetail (object)
+ Severity: Warning (string)
+ Message: `API5084 - API : {fieldName} has a {fieldName} of {value}.` (string)

## 400 Response (object)
+ Response
    + Value: 400 Bad Request (string)
+ Messages (array [400 ErrorMessageDetail])

## 400 ErrorMessageDetail (object)
+ Severity: Error (string)
+ Message: `API5058 - Data : The mandatory field {fieldName} was missing in the request body.` (string)


## 400 BadPropertyResponse (object)
+ Response
    + Value: 400 Bad Request (string)
+ Messages (array[400 BadPropertyErrorMessageDetail])

## 400 BadPropertyErrorMessageDetail (object)
+ Severity: Error (string)
+ Message: `API5074 - API : The value sent in the querystring variable {Property} is not allowed.` (string)


## 400 BadReadResponse (object)
+ Response
    + Value: 400 Bad Request (string)
+ Messages (array[400 BadReadErrorMessageDetail])

## 400 BadReadErrorMessageDetail (object)
+ Severity: Error (string)
+ Message: `API5075 - API : The value sent in the querystring is not allowed.` (string)


## 400 WarningMessageDetail (object)
+ Severity: Warning (string)
+ Message: `API50xx - Data : The field {fieldName} was not found.` (string)

## 400 InfoMessageDetail (object)
+ Severity: Information (string)
+ Message: `API50xx - Data : Now create xyz.` (string)


## 404 Response (object)
+ Response
    + Value: 404 Not Found (string)
+ Messages (array[404 ErrorMessageDetailMessage])

## 404 ErrorMessageDetailMessage (object)
+ Severity: Warning (string)
+ Message: `API5068 - Data : No records found.` (string)


## 405 Response (object)
+ Response
    + Value: 405 Method Not Allowed (string)
+ Messages (array[405 MethodNotAllowedMessage])

## 405 MethodNotAllowedMessage (object)
+ Severity: Error (string)
+ Message: `API5077 - API : That method is not supported, please check the ITAS API documentation.` (string)

## accessToken (object)
+ Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg 

## ClientAccountCreate (object)
+ ClientAccountId: ABCDE.P (string)
+ Title: ABCDE Client (string)
+ CountryCode: GB (string)
+ ShortName: ABCDE Client Ledger (string)
+ ClientTypeCode: H (string)
+ Status: H (string)
+ AddressLine1: Address Line #1 (string)
+ AddressLine2: Address Line #2 (string) 
+ AddressLine3: Address Line #3 (string) 
+ AddressLine4: Address Line #4 (string) 
+ ZipCode: 01234567 (string)
+ City: Capital (string)
+ Province: Prov (string)
+ EmailAddress: abc@def.com (string)
+ PhoneNumber: +44 1702 22334455 (string)
+ FaxNumber: +44 1702 33445566 (string)
+ CountryOfIncCode: US (string)
+ HeadOfFamilyAccountCode: HEAD.P (string)
+ CanBeBuyer: true (boolean)
+ CanBeSeller: true (boolean)
+ CanBeShipper: true (boolean)
+ CanBeWarehouse: true (boolean)
+ CanBeAgent: true (boolean)
+ CanBeDeliveryAccount: true (boolean)
+ CanBe3rdParty: true (boolean)
+ CanBeDerivativeClient: false (boolean)
+ CanBeDerivativeBroker: false (boolean)
+ CanBeIntroBroker: true (boolean)
+ CanBeBank: true (boolean)
+ CanBeDistributer: true (boolean)
+ CanBeService: true (boolean)
+ CanBeProjectSponsor: false (boolean)
+ CanBeProjectManager: false (boolean)
+ CanBeContractor: true (boolean)
+ CanBeGiveUp: true (boolean)
+ CanBeAssociation: true (boolean)
+ CanBeHaulier: true (boolean)
+ CanBeMill: true (boolean)
+ CanBeForwarder: true (boolean)
+ CanBeController: true (boolean)
+ CanBeGrower: true (boolean)
+ CanBeFloorBroker: true (boolean)
+ CanBePrivatePerson: false (boolean)
+ CanBeStockManager: false (boolean)
+ CanBeNotify: true (boolean)
+ CanBeStaff: false (boolean)
+ CanBeSampleSenderReceiver: false (boolean)
+ ClientBankAccounts (array [ClientBankAccountObject])
+ ClientInterfaceCodes (array [ClientInterfaceCodeObject])
+ ClientExtraVATRegistrations (array [ClientExtraVatObject])

## ClientAccountUpdate (object)
+ ClientAccountId: ABCDE.P (string)
+ Title: ABCDE Client (string)
+ CountryCode: GB (string)
+ ShortName: ABCDE Client Ledger (string)
+ ClientTypeCode: H (string)
+ Status: H (string)
+ AddressLine1: Address Line #1 (string)
+ AddressLine2: Address Line #2 (string) 
+ AddressLine3: Address Line #3 (string) 
+ AddressLine4: Address Line #4 (string) 
+ ZipCode: 01234567 (string)
+ City: Capital (string)
+ Province: Prov (string)
+ EmailAddress: abc@def.com (string)
+ PhoneNumber: +44 1702 22334455 (string)
+ FaxNumber: +44 1702 33445566 (string)
+ CountryOfIncCode: US (string)
+ HeadOfFamilyAccountCode: HEAD.P (string)
+ CanBeBuyer: true (boolean)
+ CanBeSeller: true (boolean)
+ CanBeShipper: true (boolean)
+ CanBeWarehouse: true (boolean)
+ CanBeAgent: true (boolean)
+ CanBeDeliveryAccount: true (boolean)
+ CanBe3rdParty: true (boolean)
+ CanBeDerivativeClient: false (boolean)
+ CanBeDerivativeBroker: false (boolean)
+ CanBeIntroBroker: true (boolean)
+ CanBeBank: true (boolean)
+ CanBeDistributer: true (boolean)
+ CanBeService: true (boolean)
+ CanBeProjectSponsor: false (boolean)
+ CanBeProjectManager: false (boolean)
+ CanBeContractor: true (boolean)
+ CanBeGiveUp: true (boolean)
+ CanBeAssociation: true (boolean)
+ CanBeHaulier: true (boolean)
+ CanBeMill: true (boolean)
+ CanBeForwarder: true (boolean)
+ CanBeController: true (boolean)
+ CanBeGrower: true (boolean)
+ CanBeFloorBroker: true (boolean)
+ CanBePrivatePerson: false (boolean)
+ CanBeStockManager: false (boolean)
+ CanBeNotify: true (boolean)
+ CanBeStaff: false (boolean)
+ CanBeSampleSenderReceiver: false (boolean)

## ClientBankAccountObject (object)
+ BankAccountName: Barclays (string)
+ BankAccountNumber: 111000111 (string)
+ CountryCode: GB (string)
+ BankNumber: 12345 (number)
+ IBANNumber: IB987654321 (string)
+ CurrencyCode: GBP (string)
+ Status: O (string)

## ClientExtraVatObject (object)
+ VATRegistrationNumber: GBP2 (string)
+ CountryCode: GB (string)
+ IDNumber: 456456 (string)
+ EORINumber: E12345 (string)

## ClientInterfaceCodeObject (object)
+ InterfaceTypeCode: SAP (string)
+ CodeMapping: SP123456 (string)
